leftnav:
- identifier: 709e24d4-f35d-7349-3b16-9c690db2b89d
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: aa6be519-5422-6b41-fc1f-de5e92c500c3
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: d2b8fae8-042d-e2e7-330b-718a84256bd7
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 9e99e6df-d344-b2f3-32e1-8e99013c0298
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 40
- identifier: 03e9d547-10f6-f6af-12da-df10d60e8247
  name: Assignments
  pageRef: /pages/assignments
  weight: 50
- identifier: fde83533-0162-9548-7d7a-b8db98c5a50b
  name: Projects
  pageRef: /pages/projects
  weight: 60
- identifier: e2538a74-eea5-808e-4258-f0a02c2a28a5
  name: Silent Game Images
  pageRef: /pages/silent-game-images
  weight: 70
- identifier: 3406ed59-5167-ffdc-3b0a-accc7c7a4565
  name: Class Log
  pageRef: /pages/class-log
  weight: 80
